export const cities = Array.from(
  new Set([
    'Agartala',
    'Agra',
    'Ahmedabad',
    'Aizawl',
    'Ajmer',
    'Alappuzha',
    'Alwar',
    'Amaravati',
    'Ambala',
    'Amritsar',
    'Anantnag',
    'Asansol',
    'Aurangabad',
    'Baramulla',
    'Bathinda',
    'Belagavi',
    'Bengaluru',
    'Berhampur',
    'Bhagalpur',
    'Bhavnagar',
    'Bhilai',
    'Bhopal',
    'Bikaner',
    'Bilaspur',
    'Bishnupur',
    'Bokaro',
    'Chandigarh',
    'Champhai',
    'Chennai',
    'Coimbatore',
    'Cuttack',
    'Dadra',
    'Daman',
    'Davanagere',
    'Dehradun',
    'Delhi',
    'Dhanbad',
    'Dharmanagar',
    'Dharamshala',
    'Dibrugarh',
    'Dimapur',
    'Diu',
    'Dispur',
    'Durg',
    'Durgapur',
    'Erode',
    'Faridabad',
    'Gandhinagar',
    'Gangtok',
    'Gaya',
    'Ghaziabad',
    'Gorakhpur',
    'Guntur',
    'Gurugram',
    'Guwahati',
    'Gwalior',
    'Gyalshing',
    'Haldwani',
    'Haridwar',
    'Hazaribagh',
    'Hisar',
    'Howrah',
    'Hubballi',
    'Hyderabad',
    'Imphal',
    'Indore',
    'Itanagar',
    'Jabalpur',
    'Jaipur',
    'Jalandhar',
    'Jammu',
    'Jamnagar',
    'Jamshedpur',
    'Jhansi',
    'Jodhpur',
    'Jorhat',
    'Jowai',
    'Karaikal',
    'Kargil',
    'Karimnagar',
    'Karnal',
    'Kavaratti',
    'Khammam',
    'Kharagpur',
    'Kochi',
    'Kohima',
    'Kolkata',
    'Kollam',
    'Korba',
    'Kota',
    'Kottayam',
    'Kozhikode',
    'Kurnool',
    'Leh',
    'Ludhiana',
    'Lunglei',
    'Lucknow',
    'Madurai',
    'Mahe',
    'Mandi',
    'Mangaluru',
    'Mapusa',
    'Margao',
    'Meerut',
    'Mohali',
    'Mokokchung',
    'Muzaffarpur',
    'Mumbai',
    'Mysuru',
    'Naharlagun',
    'Nalgonda',
    'Namchi',
    'Nashik',
    'Navi Mumbai',
    'New Delhi',
    'Nizamabad',
    'Noida',
    'Panaji',
    'Panipat',
    'Pasighat',
    'Patiala',
    'Patna',
    'Port Blair',
    'Prayagraj',
    'Puducherry',
    'Pune',
    'Puri',
    'Raipur',
    'Rajahmundry',
    'Rajkot',
    'Ranchi',
    'Roorkee',
    'Rourkela',
    'Rudrapur',
    'Sagar',
    'Salem',
    'Sambalpur',
    'Shillong',
    'Shimla',
    'Shivamogga',
    'Silchar',
    'Siliguri',
    'Silvassa',
    'Solan',
    'Solapur',
    'Srinagar',
    'Surat',
    'Thane',
    'Thanjavur',
    'Thiruvananthapuram',
    'Thoubal',
    'Thrissur',
    'Tiruchirappalli',
    'Tirunelveli',
    'Tirupati',
    'Tura',
    'Udaipur',
    'Ujjain',
    'Vadodara',
    'Varanasi',
    'Vasco da Gama',
    'Vellore',
    'Adilabad',
    'Adoni',
    'Amalapuram',
    'Anakapalle',
    'Anantapur',
    'Bapatla',
    'Bhadrachalam',
    'Bhimavaram',
    'Bobbili',
    'Bhongir',
    'Chilakaluripet',
    'Chittoor',
    'Dharmavaram',
    'Eluru',
    'Gadwal',
    'Gudivada',
    'Gudur',
    'Hindupur',
    'Jagtial',
    'Jammalamadugu',
    'Jangaon',
    'Kadapa',
    'Kakinada',
    'Kamareddy',
    'Kothagudem',
    'Kuppam',
    'Machilipatnam',
    'Madanapalle',
    'Mahabubabad',
    'Mahbubnagar',
    'Mancherial',
    'Mandapeta',
    'Medak',
    'Miryalguda',
    'Nandyal',
    'Narasaraopet',
    'Narayanpet',
    'Nellore',
    'Nirmal',
    'Ongole',
    'Peddapalli',
    'Proddatur',
    'Rajanna Sircilla',
    'Sangareddy',
    'Siddipet',
    'Srikakulam',
    'Suryapet',
    'Tadepalligudem',
    'Tadipatri',
    'Tanuku',
    'Tenali',
    'Tuni',
    'Vikarabad',
    'Vizianagaram',
    'Wanaparthy',
    'Yadadri Bhuvanagiri',
    'Yemmiganur',
    'Vijayawada',
    'Visakhapatnam',
    'Warangal',
    'Yanam',
  ]),
).sort((a, b) => a.localeCompare(b))

export const countries = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo',
  'Costa Rica',
  "Cote d'Ivoire",
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czechia',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Korea',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe',
  'Palestine',
].sort((a, b) => a.localeCompare(b))
